### ISSUE TITLE
Errors running test scripts?

### ISSUE THREAD

**Issue by stealthrabbi** [samshadwell/TrumpScript#156]
I run `python test.py` and get errors.

Many of the test files are .txt and not .tr? They can't be run without errors, e.g.

mark@MARKPC:~/TrumpScript/test/test_files$ TRUMP toupee.txt
Traceback (most recent call last):
  File "/home/mark/TrumpScript/bin/../src/trumpscript/main.py", line 30, in <module>
    main()
  File "/home/mark/TrumpScript/bin/../src/trumpscript/main.py", line 27, in main
    Compiler().compile(sys.argv[-1])
  File "/home/mark/TrumpScript/src/trumpscript/compiler.py", line 16, in compile
    modu = self.parse(self.tokenize(source))
  File "/home/mark/TrumpScript/src/trumpscript/compiler.py", line 21, in parse
    return self.prs.parse(tokens)
  File "/home/mark/TrumpScript/src/trumpscript/parser.py", line 35, in parse
    return self.handle_module(filtered)
  File "/home/mark/TrumpScript/src/trumpscript/parser.py", line 96, in handle_module
    state, tokens = self.handle_anything(tokens)
  File "/home/mark/TrumpScript/src/trumpscript/parser.py", line 110, in handle_anything
    return self._token_to_function_map[start](tokens)
  File "/home/mark/TrumpScript/src/trumpscript/parser.py", line 282, in handle_while
    body, tokens = self.handle_brace(tokens)
  File "/home/mark/TrumpScript/src/trumpscript/parser.py", line 131, in handle_brace
    cur_token = tokens.pop(0)
IndexError: pop from empty list
mark@MARKPC:~/TrumpScript/test/test_files$

mark@MARKPC:~/TrumpScript/test$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from src.trumpscript.compiler import Compiler
ImportError: No module named src.trumpscript.compiler

**Comment by stealthrabbi** [comment]
is_error
Traceback (most recent call last):
  File "/home/mark/TrumpScript/bin/../src/trumpscript/main.py", line 30, in <module>
    main()
  File "/home/mark/TrumpScript/bin/../src/trumpscript/main.py", line 27, in main
    Compiler().compile(sys.argv[-1])
  File "/home/mark/TrumpScript/src/trumpscript/compiler.py", line 18, in compile
    exec(compile(modu, filename="<ast>", mode="exec"))
TypeError: required field "lineno" missing from expr

**Comment by samshadwell** [comment]
See a76f078
