### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by benwaffle** [samshadwell/TrumpScript#33]
```
➜  TrumpScript git:(master) python3 -m src.trumpscript.main test/test_files/fizz_buzz.txt 
failed to consume 11, got 1instead.
failed to consume 11, got 20instead.
failed to consume 12, got 20instead.
failed to consume 11, got 20instead.
failed to consume 12, got 20instead.
failed to consume 11, got 20instead.
failed to consume 12, got 20instead.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/TrumpScript/src/trumpscript/main.py", line 25, in <module>
    main()
  File "/tmp/TrumpScript/src/trumpscript/main.py", line 22, in main
    src.trumpscript.compiler.Compiler().compile(sys.argv[1])
  File "/tmp/TrumpScript/src/trumpscript/compiler.py", line 18, in compile
    modu = self.parse(self.tokenize(source))
  File "/tmp/TrumpScript/src/trumpscript/compiler.py", line 25, in parse
    return self.prs.parse(tokens)
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 288, in parse
    return handle_mod()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 29, in handle_mod
    state = handle_anything()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 54, in handle_anything
    return handle_while()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 181, in handle_while
    body = handle_brace()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 77, in handle_brace
    res = handle_anything()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 52, in handle_anything
    return handle_if()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 188, in handle_if
    body = handle_brace()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 77, in handle_brace
    res = handle_anything()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 52, in handle_anything
    return handle_if()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 188, in handle_if
    body = handle_brace()
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 76, in handle_brace
    while peek() != T_RBrace:
  File "/tmp/TrumpScript/src/trumpscript/parser.py", line 15, in peek
    return tokens[0]["type"]
IndexError: list index out of range
```

**Comment by samshadwell** [comment]
So, uhh, this is the part where I say something like "we're poor college students who haven't taken either languages or compilers, and this is our compiler messing up."

We kind of don't fit our own spec right now since this was a hackathon project and we ran out of time, but we'll try to get things actually working. Definitely our bad for not having a working parser, but we didn't expect this to get as much attention as it has.

**Comment by samshadwell** [comment]
I mean, our compiler is perfect just like Trump. Must be a user error.

**Comment by benwaffle** [comment]
:person_with_blond_hair:

**Comment by CryoBrown** [comment]
Also, it looks like this error is due to some restrictions we placed on the parser at some point to simplify things during crunch time at the hackathon, when it says failed to consume 11 that means it was expecting a right parenthesis, and a left brace when it says failed to consume 12. What it's finding instead is 20, which is the IS keyword. Also, fizz-buzz is improperly written at the moment in that it doesn't check if Donald over 15000000 is nothing, it tries to assign nothing to that number literal. Also, the parser isn't written properly anyway, and I have to fix the way is works so that the left hand operator can be something other than a variable.

**Comment by CryoBrown** [comment]
But the crux of this issue is that after the expression Donald over 150000000, the parser expects to encounter the end of the parenthetical rather than another keyword. So this is the real problem underneath those other problems.

**Comment by bradneuman** [comment]
It looks to me like maybe you intended to require parens for if statements? handle_if calls handle_paren, which looks ahead for a right paren. Same problem with test_01.txt

**Comment by CryoBrown** [comment]
This is an example of deadlines in a hackathon messing with our implementation of the language spec. also we are all full-time students so it's not like we have had a lot of free time to rebuild everything
